### ISSUE TITLE
Add urlabuse.com

### ISSUE THREAD

**Issue by ps-ACA** [PeterDaveHello/threat-hostlist#2]
Hey,
urlabuse.com has a feed for cyber threats, and it's free and reputable.
 I think it should be reviewed and added.

**Comment by PeterDaveHello** [comment]
Will take a look, thanks.

**Comment by PeterDaveHello** [comment]
@ps-ACA unfortunately, it's not the host/domain format that the repository is working on, but please feel free to correct me if I'm wrong.

**Comment by ps-ACA** [comment]
process of downloading threats is fully explained on the [doc](https://urlabuse.com/doc) page.

Latest 500 entries of DB in JSON format - [data.txt](https://urlabuse.com/public/data/data.txt)
Latest 500 entries of DB in CSV format - [data_csv.txt](https://urlabuse.com/public/data/data_csv.txt)
Latest 50 entries of DB updates every 5 minutes - [data.json](https://urlabuse.com/public/data/data.json)
Latest malware URLs updates every 5 minutes - [malware_url.txt](https://urlabuse.com/public/data/malware_url.txt)
Latest phishing URLs updates every 5 minutes - [phishing_url.txt](https://urlabuse.com/public/data/phishing_url.txt)
Latest hacked URLs updates every 5 minutes - [hacked_url.txt](https://urlabuse.com/public/data/hacked_url.txt)

I have also included links to the complete database dump, malware files, page screenshots, and MISP data available on [urlabuse.com](https://urlabuse.com/).

Additional Information

I have thoroughly tested the integration of these feeds and have ensured that they are compatible with our existing security infrastructure. The [urlabuse.com](https://urlabuse.com/) feeds provide valuable threat intelligence data that will significantly enhance our security measures.
